// Sound effects.
//
// Every clip is generated by `tools/make-audio.mjs` - synthesised from maths, no downloaded
// samples. Re-run that script to change them.
//
// One entity per clip, created once. `playSound` retriggers from zero on each call, which is what
// we want for short overlapping cues.
//
// Deliberately restrained: sound fires for things the LOCAL player did or that concern the whole
// round. It never fires per-tile for remote players, or Hex-Drop would be 360 simultaneous cracks.

import { engine, Entity, Transform, AudioSource } from '@dcl/sdk/ecs'
import { Vector3 } from '@dcl/sdk/math'
import { ARENA_CENTER_X, ARENA_CENTER_Z, ARENA_Y } from '../config'

export type Clip = 'tick' | 'go' | 'crack' | 'eliminated' | 'survive' | 'crown'

export type Track = 'music-lobby' | 'music-round'

const VOLUMES: Record<Clip, number> = {
  tick: 0.35,
  go: 0.6,
  crack: 0.4,
  eliminated: 0.7,
  survive: 0.7,
  crown: 0.8
}

const sources = new Map<Clip, Entity>()
const music = new Map<Track, Entity>()
let currentTrack: Track | null = null

export function initAudio(): void {
  for (const clip of Object.keys(VOLUMES) as Clip[]) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(ARENA_CENTER_X, ARENA_Y, ARENA_CENTER_Z) })
    AudioSource.create(e, {
      audioClipUrl: 'assets/Audio/' + clip + '.wav',
      playing: false,
      loop: false,
      volume: VOLUMES[clip],
      // Global: these are feedback cues, not things happening at a place in the world. A countdown
      // that gets quieter as you walk away from the middle of the arena would be worse than useless.
      global: true
    })
    sources.set(clip, e)
  }

  for (const track of ['music-lobby', 'music-round'] as Track[]) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(ARENA_CENTER_X, ARENA_Y, ARENA_CENTER_Z) })
    AudioSource.create(e, {
      audioClipUrl: 'assets/Audio/' + track + '.wav',
      playing: false,
      loop: true,
      // Well under the cues, so music never competes with a countdown tick.
      volume: 0.22,
      global: true
    })
    music.set(track, e)
  }
}

/**
 * Cross to a music bed, or silence with `null`.
 *
 * Both beds are eight bars at 120bpm and loop seamlessly. The lobby track is calm enough to talk
 * over; the round track adds a kick and an eighth-note arpeggio to push you to move.
 */
export function setMusic(track: Track | null): void {
  if (track === currentTrack) return
  currentTrack = track
  for (const [name, entity] of music) {
    const src = AudioSource.getMutable(entity)
    src.playing = name === track
  }
}

export function play(clip: Clip): void {
  const e = sources.get(clip)
  if (!e) return
  AudioSource.playSound(e, 'assets/Audio/' + clip + '.wav')
}
