// Sound effects.
//
// Every clip is generated by `tools/make-audio.mjs` - synthesised from maths, no downloaded
// samples. Re-run that script to change them.
//
// One entity per clip, created once. `playSound` retriggers from zero on each call, which is what
// we want for short overlapping cues.
//
// Deliberately restrained: sound fires for things the LOCAL player did or that concern the whole
// round. It never fires per-tile for remote players, or Hex-Drop would be 360 simultaneous cracks.

import { engine, Entity, Transform, AudioSource } from '@dcl/sdk/ecs'
import { Vector3 } from '@dcl/sdk/math'
import { ARENA_CENTER_X, ARENA_CENTER_Z, ARENA_Y } from '../config'

export type Clip =
  | 'tick'
  | 'go'
  | 'whistle'
  | 'crack'
  | 'eliminated'
  | 'survive'
  | 'qualified'
  | 'crown'
  | 'fall'
  | 'squeak'
  | 'boing'
  | 'crowd-cheer'
  | 'crowd-aww'

/** Looping beds. The crowd bed is layered under the music rather than swapped with it. */
export type Track = 'music-lobby' | 'music-round' | 'music-tense' | 'crowd-bed' | 'music-disco'

/** Announcer lines - CC0 recordings from Kenney's Voiceover Pack, one consistent male voice. */
export type Voice =
  | 'ready'
  | 'set'
  | 'go'
  | 'you_win'
  | 'you_lose'
  | 'game_over'
  | 'congratulations'
  | 'new_highscore'
  | 'hurry_up'
  | 'final_round'

const VOICES: Voice[] = [
  'ready',
  'set',
  'go',
  'you_win',
  'you_lose',
  'game_over',
  'congratulations',
  'new_highscore',
  'hurry_up',
  'final_round'
]

const VOLUMES: Record<Clip, number> = {
  tick: 0.35,
  go: 0.6,
  whistle: 0.55,
  crack: 0.4,
  eliminated: 0.7,
  survive: 0.7,
  qualified: 0.75,
  crown: 0.8,
  fall: 0.5,
  squeak: 0.5,
  boing: 0.5,
  'crowd-cheer': 0.55,
  'crowd-aww': 0.5
}

const MUSIC: Track[] = ['music-lobby', 'music-round', 'music-tense']

const sources = new Map<Clip, Entity>()
const music = new Map<Track, Entity>()
const voices = new Map<Voice, Entity>()
let currentTrack: Track | null = null

export function initAudio(): void {
  for (const clip of Object.keys(VOLUMES) as Clip[]) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(ARENA_CENTER_X, ARENA_Y, ARENA_CENTER_Z) })
    AudioSource.create(e, {
      audioClipUrl: 'assets/Audio/' + clip + '.wav',
      playing: false,
      loop: false,
      volume: VOLUMES[clip],
      // Global: these are feedback cues, not things happening at a place in the world. A countdown
      // that gets quieter as you walk away from the middle of the arena would be worse than useless.
      global: true
    })
    sources.set(clip, e)
  }

  for (const track of [...MUSIC, 'crowd-bed'] as Track[]) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(ARENA_CENTER_X, ARENA_Y, ARENA_CENTER_Z) })
    AudioSource.create(e, {
      audioClipUrl: 'assets/Audio/' + track + '.mp3',
      playing: false,
      loop: true,
      // Music sits audibly under the cues without competing with a countdown tick. The crowd is
      // quieter still: it is the room, not the band.
      volume: track === 'crowd-bed' ? 0.28 : 0.6,
      global: true
    })
    music.set(track, e)
  }

  for (const v of VOICES) {
    const e = engine.addEntity()
    Transform.create(e, { position: Vector3.create(ARENA_CENTER_X, ARENA_Y, ARENA_CENTER_Z) })
    AudioSource.create(e, {
      audioClipUrl: 'assets/Audio/vo/' + v + '.ogg',
      playing: false,
      loop: false,
      // The announcer sits on top of everything - that is what an announcer is for.
      volume: 0.9,
      global: true
    })
    voices.set(v, e)
  }
}

/** One announcer line. Retriggers from the start if called again mid-line. */
export function say(v: Voice): void {
  const e = voices.get(v)
  if (!e) return
  AudioSource.playSound(e, 'assets/Audio/vo/' + v + '.ogg')
}

/**
 * Cross to a music bed, or silence with `null`.
 *
 * All three beds are sixteen bars at 150bpm in F sharp minor and loop seamlessly. The lobby track
 * is calm enough to talk over; the round track brings the full slap bass, breakbeat and brass.
 */
export function setMusic(track: Track | null): void {
  if (track === currentTrack) return
  currentTrack = track
  for (const name of MUSIC) {
    const src = AudioSource.getMutable(music.get(name)!)
    src.playing = name === track
  }
}

let crowdOn = false

/**
 * The stadium crowd, murmuring under the round. Fall Guys is a game show in a stadium and the
 * crowd is the thing that says so; it runs whenever a round is live and stops with it.
 */
export function setCrowd(on: boolean): void {
  if (on === crowdOn) return
  crowdOn = on
  AudioSource.getMutable(music.get('crowd-bed')!).playing = on
}

export function play(clip: Clip): void {
  const e = sources.get(clip)
  if (!e) return
  AudioSource.playSound(e, 'assets/Audio/' + clip + '.wav')
}
